runtime: nodejs16 # or another supported version

env_variables:
  ENV: "prod"

handlers:
- url: /api
  static_dir: api

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: node server.js